name: Blog post
description: Draft a blog post that auto-publishes to the site
title: "[Blog] <title>"
labels: [blog]
body:
  - type: input
    id: post_title
    attributes:
      label: Title
      placeholder: "Welcome — Site Setup and Direction"
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary (1–3 sentences)
      placeholder: "What this post covers..."
  - type: textarea
    id: content
    attributes:
      label: Content (Markdown)
      description: Full Markdown content of the post
      placeholder: "Write your post here..."
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Tags (comma-separated)
      placeholder: rails, performance, sidekiq

