name: Link check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1' # weekly Monday 05:00 UTC

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: >-
            --verbose --no-progress --max-concurrency 8
            --exclude-mail
            --accept 200,429,403
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

